title: Project

fields:
  title: Project Title
    instructions: These are instructions.

  description: 
    display: Project Description
    required: true
    default: 
    type: redactor

  date:
    display: date
    type: date

  category:
    display: Project category (wall paper or canvas)
    type: tags

  gallery:
    display: Project gallery
    type: grid
    starting_rows: 1
    min_rows: 1
    fields:
      title:
        display: Project Title
        type: text
      img:
        display: Image
        type: file
        allowed: [png, gid, jpg, jpeg]
        destination: assets/img/work
